#server:
#  port: 8081
#server:
#  servlet:
#    context-path: /test

#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1, k2: v2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2

spring:
  mvc:
    contentnegotiation:
      favor-parameter: true #开启请求参数内容协商模式